import { useState } from "react";
import { FileDown, Loader2, CheckCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { type MealPlan, type UserProfile } from "@/data/mockData";

function generateReport(plan: MealPlan, profile: UserProfile | null): string {
  const allMeals = [...plan.breakfast, ...plan.lunch, ...plan.snacks, ...plan.dinner];
  const name = profile?.name || "User";
  const date = new Date().toLocaleDateString("en", { dateStyle: "long" });

  let report = `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
          SMARTPLATE AI — DIET REPORT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Name: ${name}
  Date: ${date}
  Diet Type: ${profile?.preference || "N/A"}
  Conditions: ${profile?.diseases?.join(", ") || "None"}
  Age: ${profile?.age || "—"}  |  Weight: ${profile?.weight || "—"} kg  |  Height: ${profile?.height || "—"} cm

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                 DAILY SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Total Calories: ${plan.totalCalories} / ${plan.goalCalories} kcal
  Protein: ${plan.totalProtein}g  |  Fat: ${plan.totalFat}g  |  Carbs: ${plan.totalCarbs}g

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                   MEAL PLAN
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;

  const sections = [
    { title: "🌅 BREAKFAST", meals: plan.breakfast },
    { title: "☀️ LUNCH", meals: plan.lunch },
    { title: "🍎 SNACKS", meals: plan.snacks },
    { title: "🌙 DINNER", meals: plan.dinner },
  ];

  for (const section of sections) {
    report += `\n  ${section.title}\n  ${"—".repeat(36)}\n`;
    for (const meal of section.meals) {
      report += `  • ${meal.name}\n`;
      report += `    ${meal.calories} kcal | P: ${meal.protein}g | F: ${meal.fat}g | C: ${meal.carbs}g\n`;
      report += `    ✦ ${meal.benefits}\n\n`;
    }
  }

  if (plan.riskAlerts.length > 0) {
    report += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                 ⚠️ RISK ALERTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;

    for (const alert of plan.riskAlerts) {
      const icon = alert.severity === "high" ? "🔴" : "🟡";
      report += `  ${icon} ${alert.food} (${alert.disease})\n`;
      report += `     ${alert.message}\n\n`;
    }
  }

  report += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Generated by SmartPlate AI on ${date}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;

  return report;
}

export function ReportGenerator({ plan, profile }: { plan: MealPlan; profile: UserProfile | null }) {
  const [loading, setLoading] = useState(false);
  const [done, setDone] = useState(false);

  const handleDownload = () => {
    setLoading(true);
    setTimeout(() => {
      const text = generateReport(plan, profile);
      const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `SmartPlate_Report_${new Date().toISOString().split("T")[0]}.txt`;
      a.click();
      URL.revokeObjectURL(url);
      setLoading(false);
      setDone(true);
      setTimeout(() => setDone(false), 3000);
    }, 800);
  };

  return (
    <Button
      onClick={handleDownload}
      disabled={loading}
      variant="outline"
      className="w-full h-12 rounded-2xl border-primary/30 text-primary font-bold hover:bg-primary/5 gap-2"
    >
      {loading ? (
        <><Loader2 className="h-4 w-4 animate-spin" /> Generating...</>
      ) : done ? (
        <><CheckCircle className="h-4 w-4" /> Downloaded!</>
      ) : (
        <><FileDown className="h-4 w-4" /> Download Report</>
      )}
    </Button>
  );
}
